version: '3'
services:
  file_service:
      container_name: "file-service-container"
      image: ${NAMESPACE}/${SERVICE}:${TAG}
      build: .
      command: go run main.go
      ports:
          - "4444:4444"
      volumes:
          - .:/file-service/
      environment:
          - FIREBASE_BUCKET_NAME=xxxxx-xxxx-329303.appspot.com
          - FIREBASE_CRED_FILE_PATH=firebase-admin-key.json
          - FIREBASE_PROJECT_ID=upload-service-xxxxx
          - SERVICE_PORT=4444
          - MYSQL_DBHOST=xxxx.44.244.xxxx
          - MYSQL_DBPORT=3306
          - MYSQL_DBUSER=root
          - MYSQL_DBPASSWORD=xxx
          - MYSQL_DBNAME=db_file_service
          - MYSQL_MAX_CONNECTION=1
          - MYSQL_MAX_IDLE_CONNECTION=1
      dns:
          - 8.8.8.8
          - 8.8.4.4
      networks:
          - backend-networks
networks:
    backend-networks:
        driver: bridge
